### ISSUE TITLE
Need fontello docker for latest fontello release

### ISSUE THREAD

**Issue by theodarsamuel** [AvnerCohen/fontello_docker#1]
If you could please update the docker file to use the latest fontello release, it would be useful for me to use the latest fontello locally. I tried updating the fontello version and tried re-building it using docker. But unfortunately the URLs mentioned for mongodb retired . I am not a linux expert.

**Comment by AvnerCohen** [comment]
This should be fixed now, a latest version was pushed, fyi - mongo is no longer a dependency of fontello, so build is much simplified.

**Comment by theodarsamuel** [comment]
Thanks a lot. I will try to install it and get back to you if any issues.
